spring:
  application:
    name: waiting-api

  config:
    import:
      - database.yml
#      - monitoring.yml
      - logging.yml
#      - client-example.yml

server:
  shutdown: graceful
  port: 8080

  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
    accesslog:
      ipv6-canonical: false

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod

